version: "3.8"

services:
    # App
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # MySQL
    db:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3307:3306
        networks:
            - laravel

    # MailHog
    mailhog:
        image: mailhog/mailhog
        logging:
            driver: "none" # disable saving logs
        ports:
            - "1025:1025" # smtp server
            - "8025:8025" # web ui
        networks:
            - laravel

    # Queue
    queue:
        build:
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel

    # Redis
    redis:
        image: redis:latest
        networks:
            - laravel

    # Prometheus
    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        networks:
            - laravel

    # Grafana
    grafana:
        image: grafana/grafana
        restart: unless-stopped
        ports:
            - "3000:3000" 
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
