FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y php php-cli php-mbstring php-xml php-zip php-mysql php-sqlite3 unzip curl git && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Limpar cache de pacotes
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN chown -R jenkins:jenkins /var/jenkins_home

USER jenkins
